version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli@16
      - npm install
  pre_build:
    commands:
      - echo Running unit tests...
      - ng test --watch=false --browsers=ChromeHeadless || true  # prevents pipeline from crashing if no tests exist
  build:
    commands:
      - echo Building Angular app...
      - ng build --configuration development
  post_build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - '**/*'
  base-directory: dist/honda  # Update if needed
  discard-paths: no
